### ISSUE TITLE
Training time of SCUNet

### ISSUE THREAD

**Issue by ncbnwklrt** [cszn/SCUNet#12]
you have mention in paper that 
>  It takes about three days to train a denoising model on four NVIDIA RTX 2080 Ti GPUs.

however, in my case, it takes about 5 days to train on 4 V100 GPUs for 1200000 iterations and pics are crop into 544*544. It is much longer than 3 days. How can i speed up? thanks.

**Comment by zhongqiu1245** [comment]
@ncbnwklrt Hello, could you release your training code?
Thx!
