### ISSUE TITLE
Demo and pre-trained models on Hugging Face Spaces

### ISSUE THREAD

**Issue by NimaBoscarino** [cszn/SCUNet#15]
Hello! Your demo on Replicate is _extremely_ cool ✨ Would you be open to adding a demo on [Hugging Face Spaces](https://hf.space) as well? We've got [docs for doing that ](https://huggingface.co/docs/hub/spaces), but I'd be happy to help out with it!

If you'd like, you can also [mirror your model weights over on the Hugging Face model hub](https://huggingface.co/docs/hub/models-uploading) as well, which I know our users would love 🤗 People have been building all kinds of cool things with the models on the Hub these days, like [this demo that combines 3 different models](https://huggingface.co/spaces/ysharma/Talk_to_Multilingual_AI_WhisperBloomCoqui) 👀 

`scunet_color_real_gan` could  even be uploaded as a private or [gated model](https://huggingface.co/docs/hub/models-gated), if that's something you're interested in.

cc: @osanseviero

**Comment by cszn** [comment]
Please do it.
