### ISSUE TITLE
Will there be more models?

### ISSUE THREAD

**Issue by AIisCool** [cszn/SCUNet#2]
**Very impressed** with the results! However at times even the lowest noise reduction "15" model can remove too much detail. Will there be a "5" or "10" noise level model in the future?

Thank you for all the hard work!

**Comment by cszn** [comment]
I will provide the trained models for blind real image denoising (` scunet_color_real_psnr.pth` and ` scunet_color_real_gan.pth`) upon request via email.

**Comment by AIisCool** [comment]
Thank you, I have sent an email to you.
