### ISSUE TITLE
Could you please implement --tile option in code?

### ISSUE THREAD

**Issue by zelenooki87** [cszn/SCUNet#4]
With RTX 3060 I am unable to denoise images >4Mpx...For very low resolutions, results are impressive. 

Thank you

**Comment by cszn** [comment]
Try this
https://github.com/cszn/SCUNet/blob/3d5c19e93ab5723b28a839fe57ee274dd6ae6daa/main_test_scunet_real_application.py#L99

**Comment by zelenooki87** [comment]
I uncommented # in this line you mentioned, but same Cuda out of memory error. Exactly in same MB as before uncommenting. Tried also smaller number like refield=8, min_size=128, same error and same Mb out of... please suggest me what to do ...
Thanks

**Comment by sun-jiao** [comment]
Same problem here. Any updates?

**Comment by sun-jiao** [comment]
OK. I read the code and have understood it. You should uncomment this line as well as comment the next line. @zelenooki87
