### ISSUE TITLE
边缘异常

### ISSUE THREAD

**Issue by compwang** [cszn/SCUNet#5]
ReplicationPad2d 改为ReplicationPad2d可以避免部分case的边缘异常

**Comment by cszn** [comment]
Try this
https://github.com/cszn/SCUNet/blob/3d5c19e93ab5723b28a839fe57ee274dd6ae6daa/main_test_scunet_real_application.py#L99

**Comment by sun-jiao** [comment]
Could I know what you mean by "change ReplicationPad2d to ReplicationPad2d"? It seems that the former and the latter are both "ReplicationPad2d".

请问您所说的"ReplicationPad2d 改为ReplicationPad2d"是什么意思?看起来前者和后者都是"ReplicationPad2d".
